# Generated by Django 6.1 on 2026-08-19 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active_investigation', 'Active Investigation'), ('pending_review', 'Pending Review'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=30)),
                ('classification', models.CharField(choices=[('unclassified', 'Unclassified'), ('class_a', 'Class A — Apparition'), ('class_b', 'Class B — Residual Haunting'), ('class_c', 'Class C — Intelligent Haunting'), ('class_d', 'Class D — Poltergeist'), ('class_e', 'Class E — Demonic'), ('debunked', 'Debunked — Natural Explanation')], default='unclassified', max_length=30)),
                ('weather_conditions', models.CharField(blank=True, help_text='Weather at time of investigation', max_length=200)),
                ('moon_phase', models.CharField(blank=True, max_length=50)),
                ('electromagnetic_baseline', models.FloatField(blank=True, help_text='Baseline EMF reading in mG', null=True)),
                ('temperature_baseline', models.FloatField(blank=True, help_text='Baseline temperature in °F', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='investigator.case')),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EVPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='EVP Recording', max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='evp/%Y/%m/%d/')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('recorder_location', models.CharField(blank=True, help_text='Where the recorder was placed', max_length=200)),
                ('emf_at_recording', models.FloatField(blank=True, help_text='EMF level at time of recording (mG)', null=True)),
                ('temperature_at_recording', models.FloatField(blank=True, help_text='Temperature at recording (°F)', null=True)),
                ('investigator_notes', models.TextField(blank=True)),
                ('has_potential_evp', models.BooleanField(default=False)),
                ('evp_transcript', models.TextField(blank=True, help_text='Transcribed or suspected EVP words/phrases')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evp_sessions', to='investigator.investigationsession')),
            ],
            options={
                'verbose_name': 'EVP Session',
                'verbose_name_plural': 'EVP Sessions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('photo', 'Photograph'), ('video', 'Video'), ('audio', 'Audio Recording'), ('document', 'Document / Notes'), ('screenshot', 'Screenshot'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('classification', models.CharField(choices=[('anomaly', 'Anomaly Detected'), ('class_a', 'Class A — Clear Evidence'), ('class_b', 'Class B — Possible Evidence'), ('class_c', 'Class C — Inconclusive'), ('debunked', 'Debunked')], default='class_c', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='investigator.investigationsession')),
            ],
            options={
                'verbose_name': 'Evidence Item',
                'verbose_name_plural': 'Evidence Items',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EMFReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_mg', models.FloatField(help_text='EMF level in milligauss')),
                ('location_description', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emf_readings', to='investigator.investigationsession')),
            ],
            options={
                'verbose_name': 'EMF Reading',
                'verbose_name_plural': 'EMF Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(default='accelerometer', help_text='Type of sensor that triggered', max_length=50)),
                ('trigger_value', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='investigator.investigationsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
